repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: forbid-submodules
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.20.1
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: forbid-environments
        name: Check for included environments
        entry: Environment directories for conda, virtualenv, or renv should not be included in commits
        language: fail
        files: "(conda-meta|pyvenv.cfg|renv/library)"
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9001
    hooks:
      - id: style-files
      - id: parsable-R
ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
