version: 0.0
os: linux

files:
  - source: /
    destination: /opt/nextflow
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /opt/nextflow
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: ./scripts/tmux_launch.sh
      timeout: 300
      runas: ec2-user
