name: Check nextflow stub

on:
  push:
    branches:
      - jashapiro/resourceLimits
  pull_request:
    branches:
      - main

jobs:
  nf-stub-check:
    runs-on: ubuntu-latest
    container: nextflow/nextflow:24.04.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check main workflow
        run: nextflow run main.nf -stub -profile stub -ansi-log false -log stub-run.log

      - name: Check simulate workflow
        run: nextflow run main.nf -stub -profile stub -entry simulate -ansi-log false -log simulate-run.log

      - name: Join log files
        if: ${{ !cancelled() }}
        run: cat stub-run.log simulate-run.log > nextflow-runs.log

      - name: Upload nextflow log
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: nextflow-log
          path: nextflow-runs.log
