name: Check nextflow stub

on:
  push:
    branches:
      - jashapiro/resourceLimits
  pull_request:
    branches:
      - main

jobs:
  nf-stub-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check main workflow
        uses: docker://nextflow/nextflow:24.04.2
        with:
          args: nextflow -log stub-run.log run main.nf -stub -profile stub -ansi-log false

      - name: Check simulate workflow
        uses: docker://nextflow/nextflow:24.04.2
        with:
          args: nextflow -log simulate-run.log run main.nf -stub -profile stub -ansi-log false -entry simulate

      - name: Join log files
        if: ${{ !cancelled() }}
        run: cat stub-run.log simulate-run.log > nextflow-runs.log

      - name: Upload nextflow log
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: nextflow-log
          path: nextflow-runs.log
