name: Batch CodeDeploy CI

on:
  push:
    tags: [v*.*.*]
  workflow_dispatch:
    inputs:
      revision:
        description: "branch or tag to deploy"
        required: true
        default: "main"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Run Code Deploy Job
    runs-on: ubuntu-latest
    environment: "prod"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382809252:role/GithubOpenId-nextflow
          role-session-name: githubActionSession
          aws-region: us-east-1

      - name: Create tmux launch script
        env:
          # use the github tag if a push event, or the workflow input if a manual trigger
          revision: ${{ github.event_name == 'push' && github.ref_name || inputs.revision }}
        run: |
          echo '#!/bin/bash' > scripts/tmux_launch.sh
          echo "export GITHUB_TAG=$revision" >> scripts/tmux_launch.sh
          echo 'tmux new-session -d -s nextflow /opt/nextflow/scripts/run_nextflow.sh' >> scripts/tmux_launch.sh
          chmod +x scripts/tmux_launch.sh

      - name: Create zip archive of scripts
        run: |
          zip -r  source.zip  scripts/
        working-directory: ${{ github.workspace }}

      - name: Copy zip to S3
        run: aws s3 cp source.zip s3://pipeline-artifact-992382809252-us-east-2/
        env:
          AWS_DEFAULT_REGION: us-east-2

      - name: Trigger AWS CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name Batch \
            --deployment-group-name Batch-deployment-group \
            --s3-location bucket=pipeline-artifact-992382809252-us-east-2,key=source.zip,bundleType=zip \
            --region us-east-2
        env:
          AWS_DEFAULT_REGION: us-east-2
